export const stories = [
    {
		"story": {
			"targetLanguage": "小猫的冒险|从前有一只小猫叫做咪咪。咪咪是一个勇敢的猫，它喜欢探险。一天，咪咪决定去探索附近的森林。它跳着去了森林，想要看看新的地方。\n\n咪咪在森林里看到了很多美丽的花朵和高大的树木。但是，突然间，一只大狗出现了！咪咪吓得跑得飞快，躲进了一个洞穴里。\n\n在洞穴里，咪咪发现了一只小老鼠。它们开始交谈，原来小老鼠也是来森林探险的。他们变成了好朋友，一起探索了洞穴。\n\n不久，他们听到了一阵巨大的声音。原来是一只大熊！咪咪和小老鼠吓得不知所措。但是，咪咪决定勇敢地面对熊。它发出了一声可爱的“喵喵”声，熊被咪咪的勇气和可爱感动了。\n\n于是，熊变成了他们的朋友，一起保护他们。咪咪和小老鼠从洞穴出来，继续他们的探险之旅。他们学到了很多东西，也交到了新朋友。\n\n最后，咪咪和小老鼠安全地回到了家。它们的冒险结束了，但是他们的友谊会一直持续下去。\n\n这是咪咪和小老鼠的冒险故事，一个关于勇气、友谊和探险的故事。",
			"english": "The Little Cat's Adventure|Once upon a time, there was a little cat named Mimi. Mimi was a brave cat, and she loved adventure. One day, Mimi decided to explore the nearby forest. She hopped into the forest, eager to see new places.\n\nIn the forest, Mimi saw many beautiful flowers and tall trees. But suddenly, a big dog appeared! Mimi got scared and ran into a cave as fast as she could.\n\nIn the cave, Mimi found a little mouse. They started talking, and it turned out the mouse was also exploring the forest. They became good friends and explored the cave together.\n\nBefore long, they heard a loud noise. It was a big bear! Mimi and the mouse were scared and didn't know what to do. But Mimi decided to bravely face the bear. She made a cute \"meow\" sound, and the bear was touched by Mimi's courage and cuteness.\n\nSo, the bear became their friend and protected them. Mimi and the mouse came out of the cave and continued their adventure. They learned many things and made new friends.\n\nFinally, Mimi and the mouse safely returned home. Their adventure ended, but their friendship would continue forever.\n\nThis is the adventure story of Mimi and the mouse, a story about courage, friendship, and exploration."	
		},
		"difficulty": "beginner",
		"language": "chinese"
	},
	{
		"story": {
			"targetLanguage": "在北京的一所学校里，有一个叫小明的学生。小明是一个很好学的孩子，他每天都很用功。今天是星期一，小明早早地就起床了，因为他知道今天有一场重要的考试。 小明来到学校，看见了他的老师和同学们都在准备考试。他们都很认真，因为这次考试对他们的成绩很重要。 考试开始了，小明很专心地答题。他把知道的都写了下来，对不知道的问题，他又认真地思考。考试结束后，大家都松了一口气。 下午，小明的老师告诉他们，他们这次考试的成绩都很好。小明很高兴，因为他知道自己的努力没有白费。 放学后，小明和他的朋友们一起去商店买了一些零食庆祝考试顺利结束。大家在商店里笑着谈笑着，度过了愉快的时光。 回到家里，小明的妈妈为他准备了一顿丰盛的晚餐。小明感到很幸福，他知道自己有一个爱他的家庭，一个支持他的妈妈。 晚上，小明躺在床上回想今天发生的一切，他觉得自己很幸运。他决定明天继续努力学习，因为他知道只有这样，才能实现自己的梦想。",
			"english": "In a school in Beijing, there is a student named Xiao Ming. Xiao Ming is a very diligent child, and he works hard every day. Today is Monday, and Xiao Ming woke up early because he knew there was an important exam today. Xiao Ming arrived at school and saw that his teacher and classmates were all preparing for the exam. They were all very serious because this exam was important for their grades. The exam began, and Xiao Ming focused on answering the questions. He wrote down everything he knew, and for the questions he didn't know, he thought carefully. After the exam, everyone breathed a sigh of relief. In the afternoon, Xiao Ming's teacher told them that everyone did well on the exam. Xiao Ming was happy because he knew his efforts had paid off. After school, Xiao Ming and his friends went to the store to buy some snacks to celebrate the successful end of the exam. Everyone laughed and talked in the store, enjoying the pleasant time together. Back home, Xiao Ming's mother prepared a delicious dinner for him. Xiao Ming felt very happy, knowing he had a loving family and a supportive mother. At night, Xiao Ming lay in bed and thought about everything that happened today. He felt fortunate and decided to continue working hard tomorrow because he knew that's the only way he could achieve his dreams."
		},
		"difficulty": "beginner",
		"language": "chinese"
	}
]